CREATE TABLE TDESPESA (
	codigoDespesa BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	dataDespesa DATE NOT NULL,
	valor DECIMAL(14,2) NOT NULL,
	tipoDespesa VARCHAR(50) NOT NULL,
	formaPagamento VARCHAR(50) NOT NULL,
	observacao VARCHAR(255) NULL	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
