CREATE TABLE TCARTAO (
	codigoCartao BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	tipoCartao VARCHAR(50) NOT NULL,
	bandeira VARCHAR(50) NOT NULL,
	codigoSeguranca VARCHAR(5) NOT NULL,
	numeroCartao VARCHAR(50) NOT NULL,
	dataVencimento DATE NOT NULL,
	nomeCartao VARCHAR(50) NOT NULL,
	limite DECIMAL(14,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
