CREATE TABLE TTARIFA (
	codigoTarifa BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome DATE NOT NULL,
	codigoTipoTarifa BIGINT(20) NOT NULL,
	valor DECIMAL(14,2) NOT NULL,
	codigoConta BIGINT(20) NULL,
	codigoCartao BIGINT(20) NULL,
	codigoDespesa BIGINT(20) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
